# Generated by Django 5.0.3 on 2024-03-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_alter_user_email_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
